name: pokemonmap
description: "Pokemon app - find them all!"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.8
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/pokeimages/