name: pokemonmap
description: "Pokemon app - find them all!"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  dio: ^5.3.3
  insta_image_viewer: ^1.0.2
  cached_network_image: ^3.3.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  dropdown_button2: ^2.3.9
  sign_in_with_apple: ^5.0.0
  appmetrica_plugin: ^1.4.0
  flutter_launcher_icons: ^0.13.1
  skeleton_animation: ^0.1.4
  skeletonizer: ^1.1.1
  carousel_slider: ^4.2.1
  flutter_easyloading: ^3.0.5
  lazy_load_scrollview: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  buttons_tabbar: ^1.3.10
  flame: ^1.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/