import '../globals.dart';

List<Rarity> pokeRarity = [
  //todo : 1st generation
  //"Bulbasaur", "Ivysaur", "Venusaur",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Charmander", "Charmeleon", "Charizard",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Squirtle", "Wartortle", "Blastoise",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Caterpie", "Metapod", "Butterfree",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Weedle", "Kakuna", "Beedrill",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Pidgey", "Pidgeotto", "Pidgeot",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Rattata", "Raticate", "Spearow",
  Rarity.casual, Rarity.rare, Rarity.casual,
  //"Fearow", "Ekans", "Arbok",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Pikachu", "Raichu", "Sandshrew",
  Rarity.epic, Rarity.rare, Rarity.rare,
  //"Sandslash", "Nidoran♀", "Nidorina",
  Rarity.epic, Rarity.casual, Rarity.casual,
  //"Nidoqueen", "Nidoran♂", "Nidorino",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Nidoking", "Clefairy", "Clefable",
  Rarity.rare, Rarity.rare, Rarity.epic,
  //"Vulpix", "Ninetales", "Jigglypuff",
  Rarity.casual, Rarity.epic, Rarity.rare,
  //"Wigglytuff", "Zubat", "Golbat",
  Rarity.epic, Rarity.casual, Rarity.rare,
  //"Oddish", "Gloom", "Vileplume",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Paras", "Parasect", "Venonat",
  Rarity.casual, Rarity.rare, Rarity.casual,
  //"Venomoth", "Diglett", "Dugtrio",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Meowth", "Persian", "Psyduck",
  Rarity.rare, Rarity.rare, Rarity.casual,
  //"Golduck", "Mankey", "Primeape",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Growlithe", "Arcanine", "Poliwag",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Poliwhirl", "Poliwrath", "Abra",
  Rarity.casual, Rarity.rare, Rarity.rare,
  //"Kadabra", "Alakazam", "Machop",
  Rarity.rare, Rarity.epic, Rarity.casual,
  //"Machoke", "Machamp", "Bellsprout",
  Rarity.casual, Rarity.rare, Rarity.casual,
  //"Weepinbell", "Victreebel", "Tentacool",
  Rarity.casual, Rarity.rare, Rarity.casual,
  //"Tentacruel", "Geodude", "Graveler",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Golem", "Ponyta", "Rapidash",
  Rarity.rare, Rarity.rare, Rarity.epic,
  //"Slowpoke", "Slowbro", "Magnemite",
  Rarity.rare, Rarity.epic, Rarity.casual,
  //"Magneton", "Farfetch'd", "Doduo",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Dodrio", "Seel", "Dewgong",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Grimer", "Muk", "Shellder",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Cloyster", "Gastly", "Haunter",
  Rarity.rare, Rarity.rare, Rarity.rare,
  //"Gengar", "Onix", "Drowzee",
  Rarity.epic, Rarity.casual, Rarity.casual,
  //"Hypno", "Krabby", "Kingler",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Voltorb", "Electrode", "Exeggcute",
  Rarity.casual, Rarity.rare, Rarity.casual,
  //"Exeggutor", "Cubone", "Marowak",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Hitmonlee", "Hitmonchan", "Lickitung",
  Rarity.rare, Rarity.rare, Rarity.rare,
  //"Koffing", "Weezing", "Rhyhorn",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Rhydon", "Chansey", "Tangela",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Kangaskhan", "Horsea", "Seadra",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Goldeen", "Seaking", "Staryu",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Starmie", "Mr. Mime", "Scyther",
  Rarity.casual, Rarity.rare, Rarity.rare,
  //"Jynx", "Electabuzz", "Magmar",
  Rarity.rare, Rarity.rare, Rarity.rare,
  //"Pinsir", "Tauros", "Magikarp",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Gyarados", "Lapras", "Ditto",
  Rarity.epic, Rarity.epic, Rarity.rare,
  //"Eevee", "Vaporeon", "Jolteon",
  Rarity.epic, Rarity.epic, Rarity.epic,
  //"Flareon", "Porygon", "Omanyte",
  Rarity.epic, Rarity.rare, Rarity.casual,
  //"Omastar", "Kabuto", "Kabutops",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Aerodactyl", "Snorlax", "Articuno",
  Rarity.rare, Rarity.epic, Rarity.legendary,
  //"Zapdos", "Moltres", "Dratini",
  Rarity.legendary, Rarity.legendary, Rarity.epic,
  //"Dragonair", "Dragonite", "Mewtwo",
  Rarity.epic, Rarity.epic, Rarity.legendary,
  //"Mew",
  Rarity.legendary,

  //todo : 2nd generation
  //"Chikorita", "Bayleef", "Meganium",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Cyndaquil", "Quilava", "Typhlosion",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Totodile", "Croconaw", "Feraligatr",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Sentret", "Furret", "Hoothoot",
  Rarity.rare, Rarity.rare, Rarity.casual,
  //"Noctowl", "Ledyba", "Ledian",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Spinarak", "Ariados", "Crobat",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Chinchou", "Lanturn", "Pichu",
  Rarity.casual, Rarity.rare, Rarity.epic,
  //"Cleffa", "Igglybuff", "Togepi",
  Rarity.epic, Rarity.epic, Rarity.epic,
  //"Togetic", "Natu", "Xatu",
  Rarity.mystic, Rarity.casual, Rarity.casual,
  //"Mareep", "Flaaffy", "Ampharos",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Bellossom", "Marill", "Azumarill",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Sudowoodo", "Politoed", "Hoppip",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Skiploom", "Jumpluff", "Aipom",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Sunkern", "Sunflora", "Yanma",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Wooper", "Quagsire", "Espeon",
  Rarity.casual, Rarity.rare, Rarity.epic,
  //"Umbreon", "Murkrow", "Slowking",
  Rarity.epic, Rarity.casual, Rarity.epic,
  //"Misdreavus", "Unown", "Wobbuffet",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Girafarig", "Pineco", "Forretress",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Dunsparce", "Gligar", "Steelix",
  Rarity.casual, Rarity.casual, Rarity.rare,
  //"Snubbull", "Granbull", "Qwilfish",
  Rarity.casual, Rarity.rare, Rarity.casual,
  //"Scizor", "Shuckle", "Heracross",
  Rarity.rare, Rarity.rare, Rarity.rare,
  //"Sneasel", "Teddiursa", "Ursaring",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Slugma", "Magcargo", "Swinub",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Piloswine", "Corsola", "Remoraid",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Octillery", "Delibird", "Mantine",
  Rarity.casual, Rarity.casual, Rarity.epic,
  //"Skarmory", "Houndour", "Houndoom",
  Rarity.rare, Rarity.casual, Rarity.rare,
  //"Kingdra", "Phanpy", "Donphan",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Porygon2", "Stantler", "Smeargle",
  Rarity.rare, Rarity.casual, Rarity.casual,
  //"Tyrogue", "Hitmontop", "Smoochum",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Elekid", "Magby", "Miltank",
  Rarity.casual, Rarity.casual, Rarity.casual,
  //"Blissey", "Raikou", "Entei",
  Rarity.epic, Rarity.legendary, Rarity.legendary,
  //"Suicune", "Larvitar", "Pupitar",
  Rarity.legendary, Rarity.casual, Rarity.casual,
  //"Tyranitar", "Lugia", "Ho-oh",
  Rarity.casual, Rarity.legendary, Rarity.legendary,
  //"Celebi",
  Rarity.mystic,

  //todo : 3rd generation

  //todo : 4th generation

  //todo : 5th generation

  //todo : 6th generation

];