import 'package:pokemonmap/models/pokemonFolder/pokemonModel.dart';
import 'package:pokemonmap/models/pokemonUser.dart';

import '../globals.dart';

Map<Pokemon, List<Pokemon?>> pokemonNoEvolutionStage = {
  //TODO : here is all pokemons which will no evolve
  //gen 1:
  pokemonsAllList[2] : [null],
  pokemonsAllList[5] : [null],
  pokemonsAllList[8] : [null],
  pokemonsAllList[11] : [null],
  pokemonsAllList[14] : [null],
  pokemonsAllList[17] : [null],
  pokemonsAllList[19] : [null],
  pokemonsAllList[21] : [null],
  pokemonsAllList[23] : [null],
  pokemonsAllList[25] : [null],
  pokemonsAllList[27] : [null],
  pokemonsAllList[30] : [null],
  pokemonsAllList[33] : [null],
  pokemonsAllList[35] : [null],
  pokemonsAllList[37] : [null],
  pokemonsAllList[39] : [null],
  pokemonsAllList[168] : [null],
  pokemonsAllList[44] : [null],
  pokemonsAllList[181] : [null],
  pokemonsAllList[46] : [null],
  pokemonsAllList[48] : [null],
  pokemonsAllList[50] : [null],
  pokemonsAllList[52] : [null],
  pokemonsAllList[54] : [null],
  pokemonsAllList[56] : [null],
  pokemonsAllList[58] : [null],
  pokemonsAllList[61] : [null],
  pokemonsAllList[185] : [null],
  pokemonsAllList[64] : [null],
  pokemonsAllList[67] : [null],
  pokemonsAllList[70] : [null],
  pokemonsAllList[72] : [null],
  pokemonsAllList[75] : [null],
  pokemonsAllList[77] : [null],
  pokemonsAllList[79] : [null],
  pokemonsAllList[198] : [null],
  pokemonsAllList[461] : [null],
  pokemonsAllList[82] : [null],
  pokemonsAllList[84] : [null],
  pokemonsAllList[86] : [null],
  pokemonsAllList[88] : [null],
  pokemonsAllList[90] : [null],
  pokemonsAllList[93] : [null],
  pokemonsAllList[207] : [null],
  pokemonsAllList[96] : [null],
  pokemonsAllList[98] : [null],
  pokemonsAllList[100] : [null],
  pokemonsAllList[102] : [null],
  pokemonsAllList[104] : [null],
  pokemonsAllList[105] : [null],
  pokemonsAllList[106] : [null],
  pokemonsAllList[236] : [null],
  pokemonsAllList[462] : [null],
  pokemonsAllList[109] : [null],
  pokemonsAllList[463] : [null],
  pokemonsAllList[241] : [null],
  pokemonsAllList[464] : [null],
  pokemonsAllList[114] : [null],
  pokemonsAllList[229] : [null],
  pokemonsAllList[118] : [null],
  pokemonsAllList[120] : [null],
  pokemonsAllList[121] : [null],
  pokemonsAllList[211] : [null],
  pokemonsAllList[123] : [null],
  pokemonsAllList[465] : [null],
  pokemonsAllList[466] : [null],
  pokemonsAllList[126] : [null],
  pokemonsAllList[127] : [null],
  pokemonsAllList[129] : [null],
  pokemonsAllList[130] : [null],
  pokemonsAllList[131] : [null],
  pokemonsAllList[133] : [null],
  pokemonsAllList[134] : [null],
  pokemonsAllList[135] : [null],
  pokemonsAllList[195] : [null],
  pokemonsAllList[196] : [null],
  pokemonsAllList[469] : [null],
  pokemonsAllList[470] : [null],
  pokemonsAllList[699] : [null],
  pokemonsAllList[473] : [null],
  pokemonsAllList[138] : [null],
  pokemonsAllList[140] : [null],
  pokemonsAllList[141] : [null],
  pokemonsAllList[142] : [null],
  pokemonsAllList[143] : [null],
  pokemonsAllList[144] : [null],
  pokemonsAllList[145] : [null],
  pokemonsAllList[148] : [null],
  pokemonsAllList[149] : [null],
  pokemonsAllList[150] : [null],
  // gen 2 :
  pokemonsAllList[153] : [null],
  pokemonsAllList[156] : [null],
  pokemonsAllList[159] : [null],
  pokemonsAllList[161] : [null],
  pokemonsAllList[163] : [null],
  pokemonsAllList[165] : [null],
  pokemonsAllList[167] : [null],
  pokemonsAllList[170] : [null],
  pokemonsAllList[467] : [null],
  pokemonsAllList[177] : [null],
  pokemonsAllList[180] : [null],
  pokemonsAllList[183] : [null],
  pokemonsAllList[184] : [null],
  pokemonsAllList[188] : [null],
  pokemonsAllList[423] : [null],
  pokemonsAllList[191] : [null],
  pokemonsAllList[468] : [null],
  pokemonsAllList[194] : [null],
  pokemonsAllList[429] : [null],
  pokemonsAllList[200] : [null],
  pokemonsAllList[201] : [null],
  pokemonsAllList[202] : [null],
  pokemonsAllList[204] : [null],
  pokemonsAllList[205] : [null],
  pokemonsAllList[471] : [null],
  pokemonsAllList[209] : [null],
  pokemonsAllList[210] : [null],
  pokemonsAllList[212] : [null],
  pokemonsAllList[213] : [null],
  pokemonsAllList[460] : [null],
  pokemonsAllList[216] : [null],
  pokemonsAllList[218] : [null],
  pokemonsAllList[472] : [null],
  pokemonsAllList[221] : [null],
  pokemonsAllList[223] : [null],
  pokemonsAllList[224] : [null],
  pokemonsAllList[225] : [null],
  pokemonsAllList[226] : [null],
  pokemonsAllList[228] : [null],
  pokemonsAllList[231] : [null],
  pokemonsAllList[233] : [null],
  pokemonsAllList[234] : [null],
  pokemonsAllList[240] : [null],
  pokemonsAllList[242] : [null],
  pokemonsAllList[243] : [null],
  pokemonsAllList[244] : [null],
  pokemonsAllList[247] : [null],
  pokemonsAllList[248] : [null],
  pokemonsAllList[249] : [null],
  pokemonsAllList[250] : [null],
  // gen 3 :
  pokemonsAllList[253] : [null],
  pokemonsAllList[256] : [null],
  pokemonsAllList[259] : [null],
  pokemonsAllList[261] : [null],
  pokemonsAllList[263] : [null],
  pokemonsAllList[266] : [null],
  pokemonsAllList[268] : [null],
  pokemonsAllList[271] : [null],
  pokemonsAllList[274] : [null],
  pokemonsAllList[276] : [null],
  pokemonsAllList[278] : [null],
  pokemonsAllList[281] : [null],
  pokemonsAllList[474] : [null],
  pokemonsAllList[283] : [null],
  pokemonsAllList[285] : [null],
  pokemonsAllList[288] : [null],
  pokemonsAllList[290] : [null],
  pokemonsAllList[291] : [null],
  pokemonsAllList[294] : [null],
  pokemonsAllList[296] : [null],
  pokemonsAllList[475] : [null],
  pokemonsAllList[300] : [null],
  pokemonsAllList[301] : [null],
  pokemonsAllList[302] : [null],
  pokemonsAllList[305] : [null],
  pokemonsAllList[307] : [null],
  pokemonsAllList[309] : [null],
  pokemonsAllList[310] : [null],
  pokemonsAllList[311] : [null],
  pokemonsAllList[312] : [null],
  pokemonsAllList[313] : [null],
  pokemonsAllList[316] : [null],
  pokemonsAllList[318] : [null],
  pokemonsAllList[320] : [null],
  pokemonsAllList[322] : [null],
  pokemonsAllList[323] : [null],
  pokemonsAllList[325] : [null],
  pokemonsAllList[326] : [null],
  pokemonsAllList[329] : [null],
  pokemonsAllList[331] : [null],
  pokemonsAllList[333] : [null],
  pokemonsAllList[334] : [null],
  pokemonsAllList[335] : [null],
  pokemonsAllList[336] : [null],
  pokemonsAllList[337] : [null],
  pokemonsAllList[339] : [null],
  pokemonsAllList[341] : [null],
  pokemonsAllList[343] : [null],
  pokemonsAllList[345] : [null],
  pokemonsAllList[347] : [null],
  pokemonsAllList[349] : [null],
  pokemonsAllList[350] : [null],
  pokemonsAllList[351] : [null],
  pokemonsAllList[353] : [null],
  pokemonsAllList[476] : [null],
  pokemonsAllList[356] : [null],
  pokemonsAllList[357] : [null],
  pokemonsAllList[358] : [null],
  pokemonsAllList[361] : [null],
  pokemonsAllList[477] : [null],
  pokemonsAllList[364] : [null],
  pokemonsAllList[366] : [null],
  pokemonsAllList[367] : [null],
  pokemonsAllList[368] : [null],
  pokemonsAllList[369] : [null],
  pokemonsAllList[372] : [null],
  pokemonsAllList[375] : [null],
  pokemonsAllList[376] : [null],
  pokemonsAllList[377] : [null],
  pokemonsAllList[378] : [null],
  pokemonsAllList[379] : [null],
  pokemonsAllList[380] : [null],
  pokemonsAllList[381] : [null],
  pokemonsAllList[382] : [null],
  pokemonsAllList[383] : [null],
  pokemonsAllList[384] : [null],
  pokemonsAllList[385] : [null],
  //gen 4:
  pokemonsAllList[388] : [null],
  pokemonsAllList[391] : [null],
  pokemonsAllList[394] : [null],
  pokemonsAllList[397] : [null],
  pokemonsAllList[399] : [null],
  pokemonsAllList[401] : [null],
  pokemonsAllList[404] : [null],
  pokemonsAllList[408] : [null],
  pokemonsAllList[410] : [null],
  pokemonsAllList[412] : [null],
  pokemonsAllList[413] : [null],
  pokemonsAllList[415] : [null],
  pokemonsAllList[416] : [null],
  pokemonsAllList[418] : [null],
  pokemonsAllList[420] : [null],
  pokemonsAllList[422] : [null],
  pokemonsAllList[425] : [null],
  pokemonsAllList[427] : [null],
  pokemonsAllList[431] : [null],
  pokemonsAllList[434] : [null],
  pokemonsAllList[436] : [null],
  pokemonsAllList[440] : [null],
  pokemonsAllList[441] : [null],
  pokemonsAllList[444] : [null],
  pokemonsAllList[447] : [null],
  pokemonsAllList[449] : [null],
  pokemonsAllList[451] : [null],
  pokemonsAllList[453] : [null],
  pokemonsAllList[454] : [null],
  pokemonsAllList[456] : [null],
  pokemonsAllList[459] : [null],
  pokemonsAllList[478] : [null],
  pokemonsAllList[479] : [null],
  pokemonsAllList[480] : [null],
  pokemonsAllList[481] : [null],
  pokemonsAllList[482] : [null],
  pokemonsAllList[483] : [null],
  pokemonsAllList[484] : [null],
  pokemonsAllList[485] : [null],
  pokemonsAllList[486] : [null],
  pokemonsAllList[487] : [null],
  pokemonsAllList[488] : [null],
  pokemonsAllList[489] : [null],
  pokemonsAllList[490] : [null],
  pokemonsAllList[491] : [null],
  pokemonsAllList[492] : [null],
  pokemonsAllList[493] : [null],
  //gen 5:
  pokemonsAllList[496] : [null],
  pokemonsAllList[499] : [null],
  pokemonsAllList[502] : [null],
  pokemonsAllList[504] : [null],
  pokemonsAllList[507] : [null],
  pokemonsAllList[509] : [null],
  pokemonsAllList[511] : [null],
  pokemonsAllList[513] : [null],
  pokemonsAllList[515] : [null],
  pokemonsAllList[517] : [null],
  pokemonsAllList[520] : [null],
  pokemonsAllList[522] : [null],
  pokemonsAllList[525] : [null],
  pokemonsAllList[527] : [null],
  pokemonsAllList[529] : [null],
  pokemonsAllList[530] : [null],
  pokemonsAllList[533] : [null],
  pokemonsAllList[536] : [null],
  pokemonsAllList[537] : [null],
  pokemonsAllList[538] : [null],
  pokemonsAllList[541] : [null],
  pokemonsAllList[544] : [null],
  pokemonsAllList[546] : [null],
  pokemonsAllList[548] : [null],
  pokemonsAllList[549] : [null],
  pokemonsAllList[552] : [null],
  pokemonsAllList[554] : [null],
  pokemonsAllList[555] : [null],
  pokemonsAllList[557] : [null],
  pokemonsAllList[559] : [null],
  pokemonsAllList[560] : [null],
  pokemonsAllList[562] : [null],
  pokemonsAllList[564] : [null],
  pokemonsAllList[566] : [null],
  pokemonsAllList[568] : [null],
  pokemonsAllList[570] : [null],
  pokemonsAllList[572] : [null],
  pokemonsAllList[575] : [null],
  pokemonsAllList[578] : [null],
  pokemonsAllList[580] : [null],
  pokemonsAllList[583] : [null],
  pokemonsAllList[585] : [null],
  pokemonsAllList[586] : [null],
  pokemonsAllList[588] : [null],
  pokemonsAllList[590] : [null],
  pokemonsAllList[592] : [null],
  pokemonsAllList[593] : [null],
  pokemonsAllList[595] : [null],
  pokemonsAllList[597] : [null],
  pokemonsAllList[600] : [null],
  pokemonsAllList[603] : [null],
  pokemonsAllList[605] : [null],
  pokemonsAllList[608] : [null],
  pokemonsAllList[611] : [null],
  pokemonsAllList[613] : [null],
  pokemonsAllList[614] : [null],
  pokemonsAllList[616] : [null],
  pokemonsAllList[617] : [null],
  pokemonsAllList[619] : [null],
  pokemonsAllList[620] : [null],
  pokemonsAllList[622] : [null],
  pokemonsAllList[624] : [null],
  pokemonsAllList[625] : [null],
  pokemonsAllList[627] : [null],
  pokemonsAllList[629] : [null],
  pokemonsAllList[630] : [null],
  pokemonsAllList[631] : [null],
  pokemonsAllList[634] : [null],
  pokemonsAllList[636] : [null],
  pokemonsAllList[637] : [null],
  pokemonsAllList[638] : [null],
  pokemonsAllList[640] : [null],
  pokemonsAllList[641] : [null],
  pokemonsAllList[642] : [null],
  pokemonsAllList[643] : [null],
  pokemonsAllList[644] : [null],
  pokemonsAllList[645] : [null],
  pokemonsAllList[646] : [null],
  pokemonsAllList[647] : [null],
  pokemonsAllList[648] : [null],
  //gen 6:
  pokemonsAllList[651] : [null],
  pokemonsAllList[654] : [null],
  pokemonsAllList[657] : [null],
  pokemonsAllList[659] : [null],
  pokemonsAllList[662] : [null],
  pokemonsAllList[665] : [null],
  pokemonsAllList[667] : [null],
  pokemonsAllList[670] : [null],
  pokemonsAllList[672] : [null],
  pokemonsAllList[674] : [null],
  pokemonsAllList[675] : [null],
  pokemonsAllList[677] : [null],
  pokemonsAllList[680] : [null],
  pokemonsAllList[682] : [null],
  pokemonsAllList[684] : [null],
  pokemonsAllList[686] : [null],
  pokemonsAllList[688] : [null],
  pokemonsAllList[690] : [null],
  pokemonsAllList[692] : [null],
  pokemonsAllList[694] : [null],
  pokemonsAllList[696] : [null],
  pokemonsAllList[698] : [null],
  pokemonsAllList[700] : [null],
  pokemonsAllList[701] : [null],
  pokemonsAllList[702] : [null],
  pokemonsAllList[705] : [null],
  pokemonsAllList[706] : [null],
  pokemonsAllList[708] : [null],
  pokemonsAllList[710] : [null],
  pokemonsAllList[712] : [null],
  pokemonsAllList[714] : [null],
  pokemonsAllList[715] : [null],
  pokemonsAllList[716] : [null],
  pokemonsAllList[717] : [null],
  pokemonsAllList[718] : [null],
  pokemonsAllList[719] : [null],
  pokemonsAllList[720] : [null],
};

Map<Pokemon, List<Pokemon?>> pokemonEvolutionStageOne = {
  //TODO : here is all pokemons which will evolve to another if they have 30 lvl
  //gen 1 :
  pokemonsAllList[0] : [pokemonsAllList[1]],
  pokemonsAllList[3] : [pokemonsAllList[4]],
  pokemonsAllList[6] : [pokemonsAllList[7]],
  pokemonsAllList[9] : [pokemonsAllList[10]],
  pokemonsAllList[12] : [pokemonsAllList[13]],
  pokemonsAllList[15] : [pokemonsAllList[16]],
  pokemonsAllList[18] : [pokemonsAllList[19]],
  pokemonsAllList[20] : [pokemonsAllList[21]],
  pokemonsAllList[22] : [pokemonsAllList[23]],
  pokemonsAllList[171] : [pokemonsAllList[24]],
  pokemonsAllList[26] : [pokemonsAllList[27]],
  pokemonsAllList[28] : [pokemonsAllList[29]],
  pokemonsAllList[31] : [pokemonsAllList[32]],
  pokemonsAllList[172] : [pokemonsAllList[34]],
  pokemonsAllList[36] : [pokemonsAllList[37]],
  pokemonsAllList[173] : [pokemonsAllList[38]],
  pokemonsAllList[40] : [pokemonsAllList[41]],
  pokemonsAllList[42] : [pokemonsAllList[43]],
  pokemonsAllList[45] : [pokemonsAllList[46]],
  pokemonsAllList[47] : [pokemonsAllList[48]],
  pokemonsAllList[49] : [pokemonsAllList[50]],
  pokemonsAllList[51] : [pokemonsAllList[52]],
  pokemonsAllList[53] : [pokemonsAllList[54]],
  pokemonsAllList[55] : [pokemonsAllList[56]],
  pokemonsAllList[57] : [pokemonsAllList[58]],
  pokemonsAllList[59] : [pokemonsAllList[60]],
  pokemonsAllList[62] : [pokemonsAllList[63]],
  pokemonsAllList[65] : [pokemonsAllList[66]],
  pokemonsAllList[68] : [pokemonsAllList[69]],
  pokemonsAllList[71] : [pokemonsAllList[72]],
  pokemonsAllList[73] : [pokemonsAllList[74]],
  pokemonsAllList[76] : [pokemonsAllList[77]],
  pokemonsAllList[78] : [pokemonsAllList[79], pokemonsAllList[198]],
  pokemonsAllList[80] : [pokemonsAllList[81]],
  pokemonsAllList[83] : [pokemonsAllList[84]],
  pokemonsAllList[85] : [pokemonsAllList[86]],
  pokemonsAllList[87] : [pokemonsAllList[88]],
  pokemonsAllList[89] : [pokemonsAllList[90]],
  pokemonsAllList[91] : [pokemonsAllList[92]],
  pokemonsAllList[94] : [pokemonsAllList[207]],
  pokemonsAllList[95] : [pokemonsAllList[96]],
  pokemonsAllList[97] : [pokemonsAllList[98]],
  pokemonsAllList[99] : [pokemonsAllList[100]],
  pokemonsAllList[101] : [pokemonsAllList[102]],
  pokemonsAllList[103] : [pokemonsAllList[104]],
  pokemonsAllList[235] : [pokemonsAllList[105], pokemonsAllList[106], pokemonsAllList[236]],
  pokemonsAllList[107] : [pokemonsAllList[462]],
  pokemonsAllList[108] : [pokemonsAllList[109]],
  pokemonsAllList[110] : [pokemonsAllList[111]],
  pokemonsAllList[439] : [pokemonsAllList[112]],
  pokemonsAllList[113] : [pokemonsAllList[464]],
  pokemonsAllList[115] : [pokemonsAllList[116]],
  pokemonsAllList[117] : [pokemonsAllList[118]],
  pokemonsAllList[119] : [pokemonsAllList[120]],
  pokemonsAllList[438] : [pokemonsAllList[121]],
  pokemonsAllList[122] : [pokemonsAllList[211]],
  pokemonsAllList[237] : [pokemonsAllList[123]],
  pokemonsAllList[238] : [pokemonsAllList[124]],
  pokemonsAllList[239] : [pokemonsAllList[125]],
  pokemonsAllList[128] : [pokemonsAllList[129]],
  pokemonsAllList[132] : [pokemonsAllList[133], pokemonsAllList[134],
    pokemonsAllList[135], pokemonsAllList[195], pokemonsAllList[196], pokemonsAllList[469], pokemonsAllList[470], pokemonsAllList[699]],
  pokemonsAllList[136] : [pokemonsAllList[232]],
  pokemonsAllList[137] : [pokemonsAllList[138]],
  pokemonsAllList[139] : [pokemonsAllList[140]],
  pokemonsAllList[445] : [pokemonsAllList[142]],
  pokemonsAllList[146] : [pokemonsAllList[147]],
  // gen 2:
  pokemonsAllList[151] : [pokemonsAllList[152]],
  pokemonsAllList[154] : [pokemonsAllList[155]],
  pokemonsAllList[157] : [pokemonsAllList[158]],
  pokemonsAllList[160] : [pokemonsAllList[161]],
  pokemonsAllList[162] : [pokemonsAllList[163]],
  pokemonsAllList[164] : [pokemonsAllList[165]],
  pokemonsAllList[166] : [pokemonsAllList[167]],
  pokemonsAllList[169] : [pokemonsAllList[170]],
  pokemonsAllList[174] : [pokemonsAllList[175]],
  pokemonsAllList[176] : [pokemonsAllList[177]],
  pokemonsAllList[178] : [pokemonsAllList[179]],
  pokemonsAllList[297] : [pokemonsAllList[182]],
  pokemonsAllList[437] : [pokemonsAllList[184]],
  pokemonsAllList[186] : [pokemonsAllList[187]],
  pokemonsAllList[189] : [pokemonsAllList[423]],
  pokemonsAllList[190] : [pokemonsAllList[191]],
  pokemonsAllList[192] : [pokemonsAllList[468]],
  pokemonsAllList[193] : [pokemonsAllList[194]],
  pokemonsAllList[197] : [pokemonsAllList[429]],
  pokemonsAllList[199] : [pokemonsAllList[428]],
  pokemonsAllList[359] : [pokemonsAllList[201]],
  pokemonsAllList[203] : [pokemonsAllList[204]],
  pokemonsAllList[206] : [pokemonsAllList[471]],
  pokemonsAllList[208] : [pokemonsAllList[209]],
  pokemonsAllList[214] : [pokemonsAllList[460]],
  pokemonsAllList[215] : [pokemonsAllList[216]],
  pokemonsAllList[217] : [pokemonsAllList[218]],
  pokemonsAllList[219] : [pokemonsAllList[220]],
  pokemonsAllList[222] : [pokemonsAllList[223]],
  pokemonsAllList[457] : [pokemonsAllList[225]],
  pokemonsAllList[227] : [pokemonsAllList[228]],
  pokemonsAllList[230] : [pokemonsAllList[231]],
  pokemonsAllList[245] : [pokemonsAllList[246]],
  //gen 3 :
  pokemonsAllList[251] : [pokemonsAllList[252]],
  pokemonsAllList[254] : [pokemonsAllList[255]],
  pokemonsAllList[257] : [pokemonsAllList[258]],
  pokemonsAllList[260] : [pokemonsAllList[261]],
  pokemonsAllList[262] : [pokemonsAllList[263]],
  pokemonsAllList[264] : [pokemonsAllList[265], pokemonsAllList[267]],
  pokemonsAllList[269] : [pokemonsAllList[270]],
  pokemonsAllList[272] : [pokemonsAllList[273]],
  pokemonsAllList[275] : [pokemonsAllList[276]],
  pokemonsAllList[277] : [pokemonsAllList[278]],
  pokemonsAllList[279] : [pokemonsAllList[280]],
  pokemonsAllList[282] : [pokemonsAllList[283]],
  pokemonsAllList[284] : [pokemonsAllList[285]],
  pokemonsAllList[286] : [pokemonsAllList[287]],
  pokemonsAllList[289] : [pokemonsAllList[290], pokemonsAllList[291]],
  pokemonsAllList[292] : [pokemonsAllList[293]],
  pokemonsAllList[295] : [pokemonsAllList[296]],
  pokemonsAllList[298] : [pokemonsAllList[475]],
  pokemonsAllList[299] : [pokemonsAllList[300]],
  pokemonsAllList[303] : [pokemonsAllList[304]],
  pokemonsAllList[306] : [pokemonsAllList[307]],
  pokemonsAllList[308] : [pokemonsAllList[309]],
  pokemonsAllList[405] : [pokemonsAllList[314]],
  pokemonsAllList[315] : [pokemonsAllList[316]],
  pokemonsAllList[317] : [pokemonsAllList[318]],
  pokemonsAllList[319] : [pokemonsAllList[320]],
  pokemonsAllList[321] : [pokemonsAllList[322]],
  pokemonsAllList[324] : [pokemonsAllList[325]],
  pokemonsAllList[327] : [pokemonsAllList[328]],
  pokemonsAllList[330] : [pokemonsAllList[331]],
  pokemonsAllList[332] : [pokemonsAllList[333]],
  pokemonsAllList[338] : [pokemonsAllList[339]],
  pokemonsAllList[340] : [pokemonsAllList[341]],
  pokemonsAllList[342] : [pokemonsAllList[343]],
  pokemonsAllList[344] : [pokemonsAllList[345]],
  pokemonsAllList[346] : [pokemonsAllList[347]],
  pokemonsAllList[348] : [pokemonsAllList[349]],
  pokemonsAllList[352] : [pokemonsAllList[353]],
  pokemonsAllList[354] : [pokemonsAllList[355]],
  pokemonsAllList[432] : [pokemonsAllList[357]],
  pokemonsAllList[360] : [pokemonsAllList[361], pokemonsAllList[477]],
  pokemonsAllList[362] : [pokemonsAllList[363]],
  pokemonsAllList[365] : [pokemonsAllList[366], pokemonsAllList[367]],
  pokemonsAllList[370] : [pokemonsAllList[371]],
  pokemonsAllList[373] : [pokemonsAllList[374]],
  // gen 4:
  pokemonsAllList[386] : [pokemonsAllList[387]],
  pokemonsAllList[389] : [pokemonsAllList[390]],
  pokemonsAllList[392] : [pokemonsAllList[393]],
  pokemonsAllList[395] : [pokemonsAllList[396]],
  pokemonsAllList[398] : [pokemonsAllList[399]],
  pokemonsAllList[400] : [pokemonsAllList[401]],
  pokemonsAllList[402] : [pokemonsAllList[403]],
  pokemonsAllList[407] : [pokemonsAllList[408]],
  pokemonsAllList[409] : [pokemonsAllList[410]],
  pokemonsAllList[411] : [pokemonsAllList[412], pokemonsAllList[413]],
  pokemonsAllList[414] : [pokemonsAllList[415]],
  pokemonsAllList[417] : [pokemonsAllList[418]],
  pokemonsAllList[419] : [pokemonsAllList[420]],
  pokemonsAllList[421] : [pokemonsAllList[422]],
  pokemonsAllList[424] : [pokemonsAllList[425]],
  pokemonsAllList[426] : [pokemonsAllList[427]],
  pokemonsAllList[430] : [pokemonsAllList[431]],
  pokemonsAllList[433] : [pokemonsAllList[434]],
  pokemonsAllList[435] : [pokemonsAllList[436]],
  pokemonsAllList[442] : [pokemonsAllList[443]],
  pokemonsAllList[446] : [pokemonsAllList[447]],
  pokemonsAllList[448] : [pokemonsAllList[449]],
  pokemonsAllList[450] : [pokemonsAllList[451]],
  pokemonsAllList[452] : [pokemonsAllList[453]],
  pokemonsAllList[455] : [pokemonsAllList[456]],
  pokemonsAllList[458] : [pokemonsAllList[459]],
  //gen 5:
  pokemonsAllList[494] : [pokemonsAllList[495]],
  pokemonsAllList[497] : [pokemonsAllList[498]],
  pokemonsAllList[500] : [pokemonsAllList[501]],
  pokemonsAllList[503] : [pokemonsAllList[504]],
  pokemonsAllList[505] : [pokemonsAllList[506]],
  pokemonsAllList[508] : [pokemonsAllList[509]],
  pokemonsAllList[510] : [pokemonsAllList[511]],
  pokemonsAllList[512] : [pokemonsAllList[513]],
  pokemonsAllList[514] : [pokemonsAllList[515]],
  pokemonsAllList[516] : [pokemonsAllList[517]],
  pokemonsAllList[518] : [pokemonsAllList[519]],
  pokemonsAllList[521] : [pokemonsAllList[522]],
  pokemonsAllList[523] : [pokemonsAllList[524]],
  pokemonsAllList[526] : [pokemonsAllList[527]],
  pokemonsAllList[528] : [pokemonsAllList[529]],
  pokemonsAllList[531] : [pokemonsAllList[532]],
  pokemonsAllList[534] : [pokemonsAllList[535]],
  pokemonsAllList[539] : [pokemonsAllList[540]],
  pokemonsAllList[542] : [pokemonsAllList[543]],
  pokemonsAllList[545] : [pokemonsAllList[546]],
  pokemonsAllList[547] : [pokemonsAllList[548]],
  pokemonsAllList[550] : [pokemonsAllList[551]],
  pokemonsAllList[553] : [pokemonsAllList[554]],
  pokemonsAllList[556] : [pokemonsAllList[557]],
  pokemonsAllList[558] : [pokemonsAllList[559]],
  pokemonsAllList[561] : [pokemonsAllList[562]],
  pokemonsAllList[563] : [pokemonsAllList[564]],
  pokemonsAllList[565] : [pokemonsAllList[566]],
  pokemonsAllList[567] : [pokemonsAllList[568]],
  pokemonsAllList[569] : [pokemonsAllList[570]],
  pokemonsAllList[571] : [pokemonsAllList[572]],
  pokemonsAllList[573] : [pokemonsAllList[574]],
  pokemonsAllList[576] : [pokemonsAllList[577]],
  pokemonsAllList[579] : [pokemonsAllList[580]],
  pokemonsAllList[581] : [pokemonsAllList[582]],
  pokemonsAllList[584] : [pokemonsAllList[585]],
  pokemonsAllList[587] : [pokemonsAllList[588]],
  pokemonsAllList[589] : [pokemonsAllList[590]],
  pokemonsAllList[591] : [pokemonsAllList[592]],
  pokemonsAllList[594] : [pokemonsAllList[595]],
  pokemonsAllList[596] : [pokemonsAllList[597]],
  pokemonsAllList[598] : [pokemonsAllList[599]],
  pokemonsAllList[601] : [pokemonsAllList[602]],
  pokemonsAllList[604] : [pokemonsAllList[605]],
  pokemonsAllList[606] : [pokemonsAllList[607]],
  pokemonsAllList[609] : [pokemonsAllList[610]],
  pokemonsAllList[612] : [pokemonsAllList[613]],
  pokemonsAllList[615] : [pokemonsAllList[616]],
  pokemonsAllList[618] : [pokemonsAllList[619]],
  pokemonsAllList[621] : [pokemonsAllList[622]],
  pokemonsAllList[623] : [pokemonsAllList[624]],
  pokemonsAllList[626] : [pokemonsAllList[627]],
  pokemonsAllList[628] : [pokemonsAllList[629]],
  pokemonsAllList[632] : [pokemonsAllList[633]],
  pokemonsAllList[635] : [pokemonsAllList[636]],
  //gen 6:
  pokemonsAllList[649] : [pokemonsAllList[650]],
  pokemonsAllList[652] : [pokemonsAllList[653]],
  pokemonsAllList[655] : [pokemonsAllList[656]],
  pokemonsAllList[658] : [pokemonsAllList[659]],
  pokemonsAllList[660] : [pokemonsAllList[661]],
  pokemonsAllList[663] : [pokemonsAllList[664]],
  pokemonsAllList[666] : [pokemonsAllList[667]],
  pokemonsAllList[668] : [pokemonsAllList[669]],
  pokemonsAllList[671] : [pokemonsAllList[672]],
  pokemonsAllList[673] : [pokemonsAllList[674]],
  pokemonsAllList[676] : [pokemonsAllList[677]],
  pokemonsAllList[678] : [pokemonsAllList[679]],
  pokemonsAllList[681] : [pokemonsAllList[682]],
  pokemonsAllList[683] : [pokemonsAllList[684]],
  pokemonsAllList[685] : [pokemonsAllList[686]],
  pokemonsAllList[687] : [pokemonsAllList[688]],
  pokemonsAllList[689] : [pokemonsAllList[690]],
  pokemonsAllList[691] : [pokemonsAllList[692]],
  pokemonsAllList[693] : [pokemonsAllList[694]],
  pokemonsAllList[695] : [pokemonsAllList[696]],
  pokemonsAllList[697] : [pokemonsAllList[698]],
  pokemonsAllList[703] : [pokemonsAllList[704]],
  pokemonsAllList[707] : [pokemonsAllList[708]],
  pokemonsAllList[709] : [pokemonsAllList[710]],
  pokemonsAllList[711] : [pokemonsAllList[712]],
  pokemonsAllList[713] : [pokemonsAllList[714]],
};

Map<Pokemon, List<Pokemon?>> pokemonEvolutionStageTwo = {
  //TODO : here is all pokemons which will evolve to another if they have 50 lvl
  //gen 1 :
  pokemonsAllList[1] : [pokemonsAllList[2]],
  pokemonsAllList[4] : [pokemonsAllList[5]],
  pokemonsAllList[7] : [pokemonsAllList[8]],
  pokemonsAllList[10] : [pokemonsAllList[11]],
  pokemonsAllList[13] : [pokemonsAllList[14]],
  pokemonsAllList[16] : [pokemonsAllList[17]],
  pokemonsAllList[24] : [pokemonsAllList[25]],
  pokemonsAllList[29] : [pokemonsAllList[30]],
  pokemonsAllList[32] : [pokemonsAllList[33]],
  pokemonsAllList[34] : [pokemonsAllList[35]],
  pokemonsAllList[38] : [pokemonsAllList[39]],
  pokemonsAllList[41] : [pokemonsAllList[168]],
  pokemonsAllList[43] : [pokemonsAllList[44], pokemonsAllList[181]],
  pokemonsAllList[60] : [pokemonsAllList[61], pokemonsAllList[185]],
  pokemonsAllList[63] : [pokemonsAllList[64]],
  pokemonsAllList[66] : [pokemonsAllList[67]],
  pokemonsAllList[69] : [pokemonsAllList[70]],
  pokemonsAllList[74] : [pokemonsAllList[75]],
  pokemonsAllList[81] : [pokemonsAllList[461]],
  pokemonsAllList[92] : [pokemonsAllList[93]],
  pokemonsAllList[111] : [pokemonsAllList[463]],
  pokemonsAllList[112] : [pokemonsAllList[241]],
  pokemonsAllList[116] : [pokemonsAllList[229]],
  pokemonsAllList[124] : [pokemonsAllList[465]],
  pokemonsAllList[125] : [pokemonsAllList[466]],
  pokemonsAllList[232] : [pokemonsAllList[473]],
  pokemonsAllList[147] : [pokemonsAllList[148]],
  //gen 2:
  pokemonsAllList[152] : [pokemonsAllList[153]],
  pokemonsAllList[155] : [pokemonsAllList[156]],
  pokemonsAllList[158] : [pokemonsAllList[159]],
  pokemonsAllList[175] : [pokemonsAllList[467]],
  pokemonsAllList[179] : [pokemonsAllList[180]],
  pokemonsAllList[182] : [pokemonsAllList[183]],
  pokemonsAllList[187] : [pokemonsAllList[188]],
  pokemonsAllList[220] : [pokemonsAllList[472]],
  pokemonsAllList[246] : [pokemonsAllList[247]],
  // gen 3:
  pokemonsAllList[252] : [pokemonsAllList[253]],
  pokemonsAllList[255] : [pokemonsAllList[256]],
  pokemonsAllList[258] : [pokemonsAllList[259]],
  pokemonsAllList[265] : [pokemonsAllList[266]],
  pokemonsAllList[267] : [pokemonsAllList[268]],
  pokemonsAllList[270] : [pokemonsAllList[271]],
  pokemonsAllList[273] : [pokemonsAllList[274]],
  pokemonsAllList[280] : [pokemonsAllList[281], pokemonsAllList[474]],
  pokemonsAllList[287] : [pokemonsAllList[288]],
  pokemonsAllList[293] : [pokemonsAllList[294]],
  pokemonsAllList[304] : [pokemonsAllList[305]],
  pokemonsAllList[314] : [pokemonsAllList[406]],
  pokemonsAllList[328] : [pokemonsAllList[329]],
  pokemonsAllList[355] : [pokemonsAllList[476]],
  pokemonsAllList[363] : [pokemonsAllList[364]],
  pokemonsAllList[371] : [pokemonsAllList[372]],
  pokemonsAllList[374] : [pokemonsAllList[375]],
  // gen 4 :
  pokemonsAllList[387] : [pokemonsAllList[388]],
  pokemonsAllList[390] : [pokemonsAllList[391]],
  pokemonsAllList[393] : [pokemonsAllList[394]],
  pokemonsAllList[396] : [pokemonsAllList[397]],
  pokemonsAllList[403] : [pokemonsAllList[404]],
  pokemonsAllList[443] : [pokemonsAllList[444]],
  //gen 5:
  pokemonsAllList[495] : [pokemonsAllList[496]],
  pokemonsAllList[498] : [pokemonsAllList[499]],
  pokemonsAllList[501] : [pokemonsAllList[502]],
  pokemonsAllList[506] : [pokemonsAllList[507]],
  pokemonsAllList[519] : [pokemonsAllList[520]],
  pokemonsAllList[524] : [pokemonsAllList[525]],
  pokemonsAllList[532] : [pokemonsAllList[533]],
  pokemonsAllList[535] : [pokemonsAllList[536]],
  pokemonsAllList[540] : [pokemonsAllList[541]],
  pokemonsAllList[543] : [pokemonsAllList[544]],
  pokemonsAllList[551] : [pokemonsAllList[552]],
  pokemonsAllList[574] : [pokemonsAllList[575]],
  pokemonsAllList[577] : [pokemonsAllList[578]],
  pokemonsAllList[582] : [pokemonsAllList[583]],
  pokemonsAllList[599] : [pokemonsAllList[600]],
  pokemonsAllList[602] : [pokemonsAllList[603]],
  pokemonsAllList[607] : [pokemonsAllList[608]],
  pokemonsAllList[610] : [pokemonsAllList[611]],
  pokemonsAllList[633] : [pokemonsAllList[634]],
  //gen 6:
  pokemonsAllList[650] : [pokemonsAllList[651]],
  pokemonsAllList[653] : [pokemonsAllList[654]],
  pokemonsAllList[656] : [pokemonsAllList[657]],
  pokemonsAllList[661] : [pokemonsAllList[662]],
  pokemonsAllList[664] : [pokemonsAllList[665]],
  pokemonsAllList[669] : [pokemonsAllList[670]],
  pokemonsAllList[679] : [pokemonsAllList[680]],
  pokemonsAllList[704] : [pokemonsAllList[705]],
};

bool pokemonCanEvolve(PokemonUser pokemonUser) {
  final userPokemon = pokemonUser.pokemon;
  //define it so it will always have a value
  Pokemon pokemon = userPokemon;
  final level = pokemonUser.lvl;

  //we need to assign pokemon
  for(int i=0; i<pokemonsAllList.length;i++){
    if(pokemonsAllList[i].name == userPokemon.name){
      pokemon = pokemonsAllList[i];
      break;
    }
  }

  // Check if the Pokémon has no further evolution
  if (pokemonNoEvolutionStage.containsKey(pokemon)) {
    return false;
  }

  // Check if the Pokémon can evolve at stage one
  if (pokemonEvolutionStageOne.containsKey(pokemon)) {
    if (level >= 30) {
      return true;
    }
  }

  // Check if the Pokémon can evolve at stage two
  if (pokemonEvolutionStageTwo.containsKey(pokemon)) {
    if (level >= 50) {
      return true;
    }
  }

  // If no conditions met, it cannot evolve
  return false;
}

List<Pokemon?> pokemonOnWhichEvolve(PokemonUser pokemonUser) {
  final userPokemon = pokemonUser.pokemon;
  //define it so it will always have a value
  Pokemon pokemon = userPokemon;
  final level = pokemonUser.lvl;

  //we need to assign pokemon
  for(int i=0; i<pokemonsAllList.length;i++){
    if(pokemonsAllList[i].name == userPokemon.name){
      pokemon = pokemonsAllList[i];
      break;
    }
  }

  List<Pokemon?> pokemonEvolutionListToReturn = [];

  // Check if Pokémon can evolve from Stage 1 at level >= 30
  if (pokemonEvolutionStageOne.containsKey(pokemon) && level >= 30) {
    pokemonEvolutionListToReturn.addAll(pokemonEvolutionStageOne[pokemon]!);
  }

  // Check if Pokémon can evolve from Stage 2 at level >= 50
  if (pokemonEvolutionStageTwo.containsKey(pokemon) && level >= 50) {
    pokemonEvolutionListToReturn.addAll(pokemonEvolutionStageTwo[pokemon]!);
  }

  // If no evolution is possible, return [null]
  return pokemonEvolutionListToReturn;
}

PokemonUser evolvePokemonUser(PokemonUser pokemonUser, Pokemon desiredEvolution) {
  return PokemonUser(
    pokemon: desiredEvolution,
    lvl: pokemonUser.lvl,
    hashId: pokemonUser.hashId,
    pokemonExp: pokemonUser.pokemonExp
  );
}

